@startuml reset_password_sequence_diagram

actor "Admin\nSAV Manager\nSAV Technician\nScooter Owner" as u
boundary ResetPassword as v
control ForgetPassword as c
entity User as m
activate u
u -> v : FillResetPasswordForm(email,password,confirmPassword)
deactivate v
v --> u : FormFilled
activate v
v -> v :VerifyResetPasswordlForm(email,password,confirmPassword)
deactivate v
v --> v : FormVerified

alt FormVerified is true
activate v
v -> c : processForgotPassword(email,password,confirmPassword)
activate c
c -> m : updatePassword(user)
deactivate m
m --> c: password updated
deactivate c
c --> v: password updated
deactivate v
v --> u: password updated

else FormVerified is false
v --> u : showErrorMessage
deactivate c
end
@enduml