@startuml delele_role_user_class_diagram
Class user {
Int id
String name
String password
String username
String email
Bool enabled 
String verification_code
JSON Login()
Bool Register()
}

Class role{
Int id
String name
}

user .right.> role

 
Class SuperAdmin{}
Class Admin{}
Class SavManager{}
Class SavTechnician{}
Class ScooterOwner{}


top to bottom direction
user <|-- SuperAdmin
user <|-- Admin
user <|-- SavManager
user <|-- SavTechnician
user <|-- ScooterOwner


SuperAdmin "1"--"*" Admin : deleleRoleUser
SuperAdmin "1"--"*" SavManager : deleleRoleUser
SuperAdmin "1"--"*" SavTechnician : deleleRoleUser
SuperAdmin "1"--"*" ScooterOwner : deleleRoleUser






@enduml