@startuml reject_user_role_sequence_diagram

actor "Super Admin\nAdmin" as u
boundary manageUsers as v
control userController as c
entity User as m
activate u
u -> v : clickRejectButton(user)
activate v
v -> c :rejectUser(user)
activate c
c -> m :rejectUser(user)
deactivate m
m --> c: userRejected
deactivate c
c --> v: userRejected
deactivate v
v --> u: userRejected

@enduml